---
key_name: devops           # Key used for SSH
region: eu-north-1     # Region may affect response and pricing
image: ami-00381a880aa48c6c6 # look in ec2 > ami (filter owner alias: amazon) or amis of manually launched instances
id: "example testing"
instance_type: t3.micro       # Choose instance type, check AWS for pricing
sec_group: "test-security-group"